version: '4.28'

services:

  ravendb:
    container_name: marketplace-ravendb
    image: ravendb/ravendb:latest
    ports:
      - 8080:8080
    environment:
      - RAVEN_ARGS='--Setup.Mode=None'
      - RAVEN_Security_UnsecuredAccessAllowed='PrivateNetwork'

  # postgres:
  #   container_name: marketplace-postgres
  #   image: postgres
  #   ports:
  #   - 5432:5432
  #   volumes:
  #   - ./init.sql:/docker-entrypoint-initdb.d/init.sql