version: '4.1'

services:

  postgres:
    container_name: marketplace-ch8-postgres
    image: postgres
    ports:
    - 5432:5432
    environment:
      POSTGRES_DB: "Marketplace_EFCore_New"
      POSTGRES_PASSWORD: "ultim"
    volumes:
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql